version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
