// This file is autogenerated by Redwood and will be overwitten periodically

import { db } from 'src/lib/db'
import datamodel from '../../../.redwood/datamodel.json'
import { RedwoodRecord } from '@redwoodjs/record'

RedwoodRecord.db = db
RedwoodRecord.schema = datamodel

import AppInstallation from 'src/models/AppInstallation'

AppInstallation.requiredModels = []

export { AppInstallation }
