// This file is autogenerated by Redwood and will be overwitten periodically

import { db } from 'src/lib/db'
import datamodel from '../../../.redwood/datamodel.json'
import { RedwoodRecord } from '@redwoodjs/record'

RedwoodRecord.db = db
RedwoodRecord.schema = datamodel

import { AppInstallation } from 'src/models/AppInstallation'
import { OrgUsersMembership } from 'src/models/OrgUsersMembership'
import { Organization } from 'src/models/Organization'
import { User } from 'src/models/User'

AppInstallation.requiredModels = [Organization]
OrgUsersMembership.requiredModels = [Organization, User]
Organization.requiredModels = [AppInstallation, OrgUsersMembership]
User.requiredModels = [OrgUsersMembership]

export { AppInstallation, OrgUsersMembership, Organization, User }
